services:
  - type: web
    name: wgta-crypto-signals
    runtime: python
    buildCommand: |
        pip install --upgrade pip
        pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
    plan: free
