services:
  - type: web
    name: wgta-crypto-signals
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT --timeout 120 --workers 2 --threads 4"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.6
      - key: DATABASE_URL
        fromService:
          type: postgres
          name: wgta-crypto-db
          property: connectionString

  - type: postgres
    name: wgta-crypto-db
    plan: free
    ipAllowList: []  # Allow all IPs
